template:
  image: slidewiki/importservice
  restart: on-failure:5
  expose:
    - "80"
  external_links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - VIRTUAL_HOST=importservice.experimental.slidewiki.org
    - SERVICE_URL_DECK=deckservice.experimental.slidewiki.org
    - SERVICE_URL_FILE=fileservice.experimental.slidewiki.org
  volumes_from:
    - datapod
  privileged: true
